name: github-runner

services:
  github-runner:
    image: kerklangsi/github-runner:latest
    container_name: github-runner-manager
    restart: unless-stopped
    network_mode: bridge
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    environment:
      - PORT=8080
      - DATA_DIR=/app/data
      - RUNNERS_DIR=/opt/github-runners
      - RUNNER_TOOL_CACHE=/opt/hostedtoolcache
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /DATA/AppData/github-runner/data
        target: /app/data
      - type: bind
        source: /DATA/AppData/github-runner/runners
        target: /opt/github-runners
      - type: bind
        source: /DATA/AppData/github-runner/shared_data
        target: /opt/shared_data
      - type: bind
        source: /DATA/AppData/github-runner/cache
        target: /home/runner/.cache
