version: '3.8'

services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: kerklangsi/github-runner-docker:latest
    container_name: github-runner
    restart: unless-stopped
    tty: true
    stdin_open: true

    ports:
      - "${PORT:-8080}:3000"
    environment:
      - TARGET_URL=${TARGET_URL:-${REPO_URL}}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - ACCESS_TOKEN=${ACCESS_TOKEN:-${GITHUB_PAT}}
      - RUNNER_NAME=${RUNNER_NAME}
      - RUNNER_LABELS=${RUNNER_LABELS:-self-hosted,linux,x64}
      - RUNNER_GROUP=${RUNNER_GROUP:-Default}
    volumes:
      - github-runners:/opt/github-runners
      - app-data:/app/data

volumes:
  github-runners:
  app-data:
